export default {
  name: "Astropod | Free Serverless Podcast Hosting",
  about: "Astropod is an open-source template for host your podcast for free using serverless model.",
  cover: "/cover.webp",
  banner: "/banner.webp",
  author: "Manuel Ernesto",
  owner: "Manuel Ernesto",
  email: "contact.manuelernestog@gmail.com",
  language: "en",
  explicit: false,
  category: "",
  keywords: "",
  theme: "",
  listenOn: {
    spotify: "",
    googlePodcast: "",
    applePodcast: "",
    easyPodcast: "",
    amazonMusic: "",
    fountain: "",
    ivoox: "",
    pocketcasts: "",
    deezer: "",
  },
  social: {
    facebook: "",
    twitter: "",
    youtube: "",
    instagram: "",
    telegram: "",
    linkedin: "",
    newsletter: ""
  },
};
